### ISSUE TITLE
Resource size is always displayed in French

### ISSUE THREAD

**Issue by tboye** [etalab/udata-front#182]
At the moment, resource size seems to be always displayed in French, regardless of the currently chosen language. Example: `10.8Mo`

This might be related to the fact `o` suffix is hardcoded:
https://github.com/etalab/udata-front/blob/master/udata_front/frontend/resource_helpers.py#L21

**Comment by maudetes** [comment]
Thank you for the notice.
Indeed, I've made a PR to add localization of the size suffix in udata-front : https://github.com/etalab/udata-front/pull/184.
